
post_install() {
	if [ "$(sed 's|#.*||g' /etc/mkinitcpio.conf | grep HOOKS | grep mhwd-fb)" == "" ]; then
		local newHOOKS="$(sed 's|#.*||g' /etc/mkinitcpio.conf | grep HOOKS | sed 's|udev|udev mhwd-fb|' | sed 's|mhwd-fb mhwd-fb|mhwd-fb|')"	
		sed -i "/#/!s/HOOKS.*=.*/${newHOOKS}/g" /etc/mkinitcpio.conf
	fi
	if [ "$(sed 's|#.*||g' /etc/mkinitcpio.conf | grep HOOKS | grep mhwd-fb)" == "" ]; then
		echo "Please add mhwd-fb to the HOOKS array in /etc/mkinitcpio.conf"
		exit 0
	fi

	mkinitcpio -p kernel26
}


post_upgrade() {
	mkinitcpio -p kernel26
}


post_remove() {
	sed -i '/#/!s/ mhwd-fb//g' /etc/mkinitcpio.conf
	sed -i '/#/!s/mhwd-fb//g' /etc/mkinitcpio.conf

	mkinitcpio -p kernel26
}
